return {
  "nvim-treesitter/nvim-treesitter", 
  build = ":TSUpdate",
  config = function()
    local config = require("nvim-treesitter.configs")
    config.setup({
      ensure_installed = {
        "bash",
        "cpp",
        "css",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "http",
        "java",
        "php",
        "rust",
        "scss",
        "sql",
        "svelte",
        "html",
        "javascript",
        "css",
        "json",
        "jsonc",
        "lua",
        "markdown",
        "markdown_inline",
        "query",
        "elixir",
        "heex",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "luadoc",
        "luap",
        "toml",
        "vimdoc",
        "xml",
        "templ",
        "jsdoc",
        "python",
        "vue",
        "blade",
        "ruby",
        "dockerfile",
        "xml",
      },
      sync_install = false,
      auto_install = true,
      highlight = { enable = true },
      indent = { enable = true }    
    })
    -- This binds the leader key followed by i in visual mode to automatically indent the selected code.
    -- vim.api.nvim_set_keymap('v', '<leader>i', ':normal! =<CR>', { noremap = true, silent = true })
  end
}
