-- https://github.com/abhilash26/zenedit/blob/main/lua/zenedit/plugins/syntax.lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    cmd = { "TSInstall", "TSUpdate", "TSUpdateSync" },
    opts = {
      auto_install = true,
      highlight = { enable = true, additional_vim_regex_highlighting = false },
      indent = { enable = true },
      ensure_installed = {
        "bash",
        "cpp",
        "css",
        "go",
        "gomod",
        "gosum",
        "gowork",
        "graphql",
        "http",
        "java",
        "php",
        "rust",
        "scss",
        "sql",
        "svelte",
        "html",
        "javascript",
        "css",
        "json",
        "jsonc",
        "lua",
        "markdown",
        "markdown_inline",
        "query",
        "elixir",
        "heex",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "luadoc",
        "luap",
        "toml",
        "vimdoc",
        "xml",
        "templ",
        "jsdoc",
        "python",
        "vue",
        "blade",
        "ruby",
        "dockerfile",
        "xml",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.install").prefer_git = true
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
}
